### PR TITLE
Update Polylean repository

### PR DESCRIPTION
**Pull request by 0art0**
@siddhartha-gadgil I would like to update the `Polylean` repository to a more recent version of Lean. I was thinking of doing this in two steps - bringing the `lake-update` branch up to date with the `main` branch, and then merging the main branch of my fork (which has fixes for all files except `FreeModule.lean`) with `lake-update` (and eventually this will be merged with `main` once everything is fixed).

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
> @siddhartha-gadgil I would like to update the `Polylean` repository to a more recent version of Lean. I was thinking of doing this in two steps - bringing the `lake-update` branch up to date with the `main` branch, and then merging the main branch of my fork (which has fixes for all files except `FreeModule.lean`) with `lake-update` (and eventually this will be merged with `main` once everything is fixed).

I can then pull your lake-update and merge my main into it

**Comment by 0art0** [comment]
I have merged the code from the fork into `lake-update`.

**Comment by 0art0** [comment]
Yes, I will tackle this tomorrow morning.

**Comment by 0art0** [comment]
I have fixed the remaining  issues (`lake build` runs without errors locally).

**Pull request merged**
