### PR TITLE
Mathlib4 integration

### PR DESCRIPTION
**Pull request by 0art0**
## Significant changes in Polylean code
- Replacing `Morphisms.lean` with `Mathlib` declarations
- Integration with `Aesop`, especially in `MetabelianGroup.lean` and `TorsionFree.lean`
- Moving `Cocycle` code to what was formerly known as `GroupAction.lean`
- `FreeAbelianGroup` -> `AddFreeGroup` for consistency with `Mathlib` naming
- Examples section in `FreeAbelianGroup.lean` removed because of incompatibility with newer definitions
- `DecideForall` as an abbreviation (not implemented)
- Extra typeclass instances with `(priority := high)` in `GardamGroup.lean`
- Purge `ProductGroups.lean`, using product groups as defined in `Mathlib` instead
- Decouple `FreeModule` with `DecidableEq` instance (not implemented)
- Stating the Unit Conjecture in terms of fields
- Shorten proofs in `TorsionFree.lean` by `Aesop` integration
- Purge `ModArith.lean`
- Purge `IntDomain.lean`

### CODE REVIEW

**Comment by siddhartha-gadgil** [comment]
@0art0 Anything specific you wanted me to check? I assume that the statement of Gardam's theorem has not changed and CI is checking that everything compiles.

A small point: we should delete `lake_packages/manifest.json`

**Comment by 0art0** [comment]
I have actually generalised our earlier statement of the Unit conjecture using `Mathlib`'s definition of fields. Could you please check whether the `UnitConjecture.lean` file with the new changes is fine?

The `lake_packages/manifest.json` appears to be deleted already on this branch (when viewed on `GitHub`).

**Comment by siddhartha-gadgil** [comment]
I will checkout this PR and read all the code, probably on Tuesday (Jan 17)

**Comment by siddhartha-gadgil** [comment]
@0art0 What is the status of the commented out code in Metabelian group? Is it not needed anymore?
Otherwise things look good to merge.

**Review by siddhartha-gadgil — APPROVED** [review]

**Comment by 0art0** [comment]
Thanks, I will merge the code.

No, the commented out code is not needed for the main proof. I wanted to prove that the group resulting from the Metabelian construction lies in a short exact sequence, just for the sake of completeness.

**Pull request merged**
